\import Algebra.Group
\import Algebra.Group.Symmetric
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.MulOrdered
\import Algebra.Ordered
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.Graded
\import Algebra.Ring.Poly
\import Algebra.Semiring
\import Algebra.StrictlyOrdered
\import Analysis.Series
\import Arith.Complex
\import Arith.Fin
\import Arith.Fin.Order
\import Arith.Int
\import Arith.Nat
\import Arith.Rat
\import Arith.Real
\import Arith.Real.Field
\import Arith.Real.InfReal
\import Arith.Real.Root
\import Arith.Real.UpperReal
\import Data.Array
\import Data.Fin
\import Function.Meta
\import Logic
\import Logic.Classical
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Set
\import Set.Fin
\open Monoid (pow)
\open LinearlyOrderedAbGroup

\func one/3 : Real => ratio 1 3

\lemma one/3>0 : ratio 1 3 > {RealField} 0 => linarith

\lemma one/3>=0 : ratio 1 3 >= {RealField} 0 => <=-less one/3>0

\lemma one/3<1 : ratio 1 3 < {RealField} 1 => linarith

\lemma one/3<=1 : ratio 1 3 <= {RealField} 1 => <=-less one/3<1

\lemma one/2<=1 : ratio 1 2 <= {RealField} ide => linarith

\lemma one/2>=0 : ratio 1 2 >= {RealField} zro => linarith

\lemma pow1/3-strict-monotone {i k : Nat} (p : k < i) : pow one/3 i < pow one/3 k =>
  OrderedSemiring.pow_<-degree {_} {one/3} one/3>0 one/3<1 p

\lemma pow1/3-monotone {i k : Nat} (p : k <= i) : pow one/3 i <= pow one/3 k =>
  PosetSemiring.pow_<=-degree one/3>=0 one/3<=1 p

\lemma pow_one/3>0 {k : Nat} : pow one/3 (suc k) > 0 => OrderedSemiring.pow>0 one/3>0 {suc k}

\lemma pow_one/3<1/2 (m : Nat) : pow {RealField} (ratio 1 3) (suc m) < {RealField} ratio 1 2 \elim m
  | 0 => linarith
  | suc m => <∘ (<_*_positive-left (pow_one/3<1/2 m) linarith) linarith

\lemma pow_one/3<=1 {j : Nat} : pow {RealField} one/3 (suc j) <= 1 => PosetSemiring.pow<=1 one/3>=0 one/3<=1 {suc j}

\func <-cast {a b : RealField} (a<b : a RealField.< b) : a ExUpperRealAbMonoid.< b =>
  \case real_<-rat-char.1 a<b \with {
    | inP (q, A0, A1) => inP (q, A0, (Real.<=-upper {q} {b}).1 (<=-less (real_<_L.2 A1)))
  }

\func array-eps-max {n : Nat} (n>0 : n > 0) (eps : Real) (eps>0 : eps > 0) (c : Array Real n) :
  ∃ (k : Fin n) (\Pi (i : Fin n) -> c i < c k + eps) \elim n, c
  | 0, _ => \case n>0
  | 1, c => inP (0, \lam i => \let i0 : i = 0 => \case \elim i \with {
  0 => idp
  } \in rewrite i0 (
    \let A0 => transportInv (\lam x => x < c 0 + eps) (zro-right {RealAbGroup}) (<_+-right {RealAbGroup} (c 0) eps>0)
    \in rewriteI {1} (zro-right {_} {c 0}) (rewriteI {1} (zro-right {_} {c 0}) A0)))
  | suc (suc n), c0 :: cs =>
    \let | half => Real.fromRat (rat 1 2 (\case __) idp)
         | eps/2 => eps * half
         | eps2>0 : eps/2 > 0 => OrderedSemiring.<_*_positive_positive eps>0 (rat_real_<.1 idp)
    \in \case array-eps-max {suc n} NatOrder.zero<suc eps/2 eps2>0 cs \with {
    inP (k, Pk) => \case real-located {c0} {cs k - eps/2} {cs k + eps} linarith \with {
      | byLeft a => inP (0, \lam i => \case \elim i \with {
        | 0 => linarith
        | suc i => \let A0 => Pk i \in linarith
      })
      | byRight b => inP (suc k, \lam i => \case \elim i \with {
        | 0 => b
        | suc i => \let A0 => Pk i \in linarith
      })
    }
    }

\func KeyLemma {n : Nat} (eps : Real)
               (eps>0 : eps > 0)
               (a : Array Real (suc (suc n)))
               (a0>eps : a 0 > eps)
               (ai>=0 : \Pi (i : Fin (suc n)) -> a (suc i) >= 0)
               (an=1 : a (suc n) = {RealField} 1) :
  ∃ (r0 : Real) (r0>0 : r0 > 0) (k : Fin (2 * n + 4) -> Fin (suc n))
  (k_monotone : \Pi (j : Fin (2 * n + 3)) -> k (Fin.fromNat {2 * n + 3} (suc j)) <= {NatSemiring} k j)
  (C1 : a (suc (k 0)) * pow r0 (suc (k 0)) = a 0 - eps)
  (C2 : \Pi (j : Fin (2 * n + 4)) (i : Fin (suc n)) ->
    a (suc (k j)) * pow (r0 * pow one/3 j) (suc (k j)) >
    a (suc i) * pow (r0 * pow one/3 j) (suc i) - eps) =>
  \case base {n} {eps} {eps>0} {a} {a0>eps} {ai>=0} {an=1} n \with {
    | inP (k0, r0, r0>0, invC1, invC2) =>
      \let
        | l+n>=n : \Pi (l : Fin (suc n)) -> n <= l NatSemiring.+ (Fin.fromNat {n} n) =>
          \lam l => rewrite (L2 n) (transport (n <=) (+-comm {NatSemiring} {n} {l}) (<=_+ {NatSemiring} <=-refl zero<=_))
        | N => 2 * n + 3
      \in \case finiteDependentChoice {\Sigma (j : Nat) (kj : Fin (suc n)) (P : ineq r0 j kj)}
                  (\lam (j, kj, Pj) (j+1,kj+1,Pj+1) => \Sigma (kj+1 <= {NatSemiring} kj) (j+1 = {NatSemiring} suc j))
                  (0, k0, \lam l => rewrite ide-right (invC2 l (l+n>=n l))) (step r0 r0>0) N \with {
        | inP (f, p, mon) =>
          inP (r0,
               r0>0,
               \lam j => (f j).2,
               \lam j => rewrite (fin_mod_id (suc j)) (mon j).1,
               rewrite p invC1,
               \lam j => rewrite (sucPreserving-isId {N} (\lam k => (f k).1) (\lam k => (mon k).2) (pmap __.1 p) j) in (f j).3)
      }
  } \where {
  \func sucPreserving-isId {n : Nat} (f : Fin (suc n) -> Nat)
                           (plus1 : \Pi (x : Fin n) -> f (suc x) = suc (f x))
                           (f0 : f 0 = 0) (x : Fin (suc n)) : f x = {NatSemiring} x \elim x
    | 0 => f0
    | suc x => plus1 x *> pmap suc (sucPreserving-isId f plus1 f0 x)

  \func step (r0 : Real) (r0>0 : r0 > 0) :
    \Pi (tuple_j : \Sigma (j : Nat) (kj : Fin (suc n)) (ineq r0 j kj)) ->
      ∃ (tuple_j+1 : \Sigma (j+1 : Nat) (kj+1 : Fin (suc n)) (ineq r0 j+1 kj+1))
      (\Sigma (tuple_j+1.2 <= {NatSemiring} tuple_j.2) (tuple_j+1.1 = {NatSemiring} suc tuple_j.1)) =>
    \lam (j, kj, IH) =>
      \let
        | eps/2 : Real => eps * ratio 1 2
        | eps-eps/2 : eps/2 - eps = negative eps/2 => AddGroup.cancel-left eps/2 (rewrite (AddGroup.toZero idp, inv +-assoc, inv Ring.ldistr, RealAbGroup.half+half {1}, ide-right) (AddGroup.toZero idp))
        | eps2>0 : eps/2 > 0 => OrderedSemiring.<_*_positive_positive eps>0 (rat_real_<.1 idp)
        | -eps2-eps2=-eps : negative eps/2 + negative eps/2 = negative eps => rewrite (inv AbGroup.negative_+-comm, inv ldistr, RealAbGroup.half+half {1}, ide-right) idp
        | r : Real => r0 * pow one/3 j
        | r>0 : r > {RealField} 0 => OrderedSemiring.<_*_positive_positive r0>0 (OrderedSemiring.pow>0 one/3>0 {j})
        | rNext : Real => r0 * pow one/3 (suc j)
        | rNext=r/3 : rNext = r * one/3 => inv *-assoc
        | kLen : Nat => suc kj
        | kLen<= : kLen <= suc n => suc_<_<= (fin_< kj)
        | c : Array Real kLen => mkArray (\lam t => a (suc (fin-inc_<= kLen<= t)) * pow rNext (suc (fin-inc_<= kLen<= t)))
      \in \case array-eps-max {kLen} NatOrder.zero<suc eps/2 eps2>0 c \with {
        | inP (k', Pk') =>
          \let
            | k'<kj : k' <= {NatSemiring} kj => suc<=suc.conv (suc_<_<= (fin_< k'))
            | k'<n+1 : k' < {NatSemiring} suc n => <∘r {NatSemiring} {k'} {kj} {suc n} k'<kj (fin_< kj)
            | kj+1 : Fin (suc n) => fin-inc_<= kLen<= k'
            | kj+1<=kj : kj+1 <= {NatSemiring} kj => rewrite toFin=id k'<kj
            | max-eps/2 : \Pi (t : Fin kLen) ->
              a (suc (fin-inc_<= kLen<= k')) * pow rNext (suc (fin-inc_<= kLen<= k')) >
              a (suc (fin-inc_<= kLen<= t)) * pow rNext (suc (fin-inc_<= kLen<= t)) - eps/2 => \lam t => \let A0 => Pk' t \in linarith
            | A0 : kj+1 LinearOrder.<= {NatSemiring} toFin k' {suc n} k'<n+1 => rewrite toFin=id (<=-refl {NatSemiring})
          \in inP ((suc j, kj+1, \lam i =>
            \let
              | LE (i<kLen : (i : Nat) < kLen) =>
                \let
                  | t : Fin kLen => toFin i i<kLen
                  | inc_t=i : fin-inc_<= kLen<= t = {Fin (suc n)} i => fin_nat-inj (toFin=id *> inv (rewrite toFin=id idp))
                \in <_+-left (negative eps) (rewrite inc_t=i in Pk' t)
            \in \case LinearOrder.trichotomy i kj \with {
              | less i<kj => <∘ (LE linarith) (rewrite (+-assoc, eps-eps/2) linarith) -- <∘ (LE linarith) (rewrite (+-assoc, eps-eps/2) linarith)
              | equals i=kj => <∘ (LE (rewrite i=kj id<suc)) (rewrite (+-assoc, eps-eps/2) linarith)
              | greater kj<i =>
                \let
                  | eps*1/3^kj<eps/2 : eps * pow one/3 (suc kj) < eps/2 => <_*_positive-right eps>0 (pow_one/3<1/2 kj)
                  | A3 : a (suc i) * pow rNext (suc i) - eps RealField.< a (suc kj) * pow rNext (suc kj) - eps/2 =>
                    rewrite (rNext=r/3, CMonoid.pow_*-comm {_} {r} {one/3} {suc i}, CMonoid.pow_*-comm {_} {r} {one/3} {suc kj})
                      (rewriteI (*-assoc {_} {a (suc i)}, *-assoc {_} {a (suc kj)}) (rewrite (+-assoc, -eps2-eps2=-eps) in
                      <_+-left {_} (negative eps/2) ( <-transitive (LinearlyOrderedAbMonoid.<=_+-left (<=_*_positive-right (PosetSemiring.<=_*_positive_positive (ai>=0 i)
                        (PosetSemiring.pow>=0 {RealField} {r} {suc i} (<=-less r>0))) (<=-less (pow1/3-strict-monotone (NatOrder.<.suc<suc kj<i))))
                        (OrderedAddGroup.negative_< eps*1/3^kj<eps/2))
                        (rewrite PseudoRing.rdistr_- in <_*_positive-left (IH i) pow_one/3>0))))
                  | fin-inc_kj : fin-inc_<= kLen<= (toFin kj id<suc) = kj => fin_nat-inj (rewrite toFin=id toFin=id) \in
                  <∘ A3 (rewrite (+-assoc, AddGroup.toZero idp, zro-right, fin-inc_kj) in <_+-left (negative eps/2) (Pk' (toFin kj id<suc)))
            }), (kj+1<=kj, idp))
      }

  \func ineq(r0 : Real) (j : Nat) (kj : Fin (suc n)) =>
    \Pi (i : Fin (suc n)) -> a (suc kj) * pow (r0 * pow one/3 j) (suc kj) > a (suc i) * pow (r0 * pow one/3 j) (suc i) - eps

  \lemma L1 {n : Nat} : suc (Fin.fromNat {n} n) = {Fin (suc (suc n))} suc n =>
    nat_fin_= (rewrite (L2 n, mod_< id<suc) idp)

  \lemma L2 (n : Nat) : Fin.fromNat {n} n = {Nat} n =>
    unfold Fin.fromNat (mod_< id<suc)

  \lemma L3 {n : Nat} {m l : Fin (suc n)} (l+m=n : l NatSemiring.+ m = {NatSemiring} n) : n - {FinRing} m = {Fin (suc n)} l =>
    AddGroup.cancel-right {FinRing} m (rewrite (nat_fin_= {suc n} {n} {l + m} (inv (rewrite l+m=n idp)))
      ((rewrite (negative-left {FinRing} {m}) in +-assoc {FinRing} {l Nat.+ m} {negative m} {m}) *> zro-right))

  \func base (m : Fin (suc n)) :
    ∃ (k0 : Fin (suc n)) (r0 : Real) (r0>0 : r0 > 0)
    (a (suc k0) * pow r0 (suc k0) = a 0 - eps)
    (\Pi (l : Fin (suc n)) (l NatSemiring.+ m >= n) ->
      a (suc k0) * pow r0 (suc k0) > a (suc l) * pow r0 (suc l) - eps) \elim m
    | 0 =>
      \let | A0 => pow_root {suc n} suc/=0 {a 0 - eps} (\let A1 => a0>eps \in linarith)
      \in inP (n, root (suc n) (a 0 - eps), root>0 (\lam _ => linarith) linarith, rewrite L1 (rewrite {3} L2 (rewrite (A0, an=1, ide-left) idp)),
               \lam l A2 =>
                 \let
                   | A3 : \Pi {x : Real} -> x - eps < x => \let eps>0 => eps>0 \in \lam {_} => linarith
                   | A4 => rewrite (AddGroup.minus_zro, zro-left) in L3 {n} {0} {l}
                   | A5 : l < {NatSemiring} Nat.suc n => rewriteI (fin_mod_id l) (mod<right (\lam _ => linarith))
                   | A6 : l = {Fin (suc n)} n => inv (A4 (<=-antisymmetric (suc<=suc.conv (suc_<_<= A5)) (rewrite zro-right in A2)))
                 \in rewrite (A6, L1) A3)
    | suc m => \case base m \with {
      | inP (k0, r0, r0>0, A0, A1) =>
        \let
          | i => n - {FinRing} suc m
          | eps>0 => eps>0
          | a0-eps>0 : a 0 - eps > 0 => \let A2 => a0>eps \in linarith \in
          \case real-located {a (suc i) * pow r0 (suc i)} {a 0 - eps} {a 0} linarith \with {
            | ||.byLeft A2 =>
              \let
                | r0^i+1>0 => OrderedSemiring.pow>0 r0>0 {suc i}
                | r0^-i-1 => OrderedField.pinv (pow {RealField} r0 (suc i)) r0^i+1>0
                | ai+1>0 => rewrite (*-assoc, OrderedField.pinv-right, ide-right) in OrderedSemiring.<_*_positive_positive {RealField} {_} {r0^-i-1} (<∘ a0-eps>0 A2) (OrderedField.pinv>0 r0^i+1>0)
                | A3 => OrderedSemiring.<_*_positive_positive a0-eps>0 (OrderedField.pinv>0 ai+1>0)
                | i+1/=0 : suc i /= {Nat} 0 => \case __
                | r0new => root (suc i) ((a 0 - eps) * OrderedField.pinv (a (suc i)) ai+1>0)
                | r0new<r0 => rewrite (root_pow i+1/=0 (<=-less r0>0)) in
                root-monotone i+1/=0 (<=-less A3)
                  (rewriteI (RealField.ide-right {pow {RealField} r0 (suc i)}, OrderedField.pinv-right {_} {a (suc i)} ai+1>0, *-assoc)
                    (<_*_positive-left (rewrite *-comm A2) (OrderedField.pinv>0 ai+1>0)))
                | A4 : a (suc i) RealField.* (pow {RealField} r0new i RealField.* r0new) = {Real} a 0 - {RealField} eps =>
                  rewrite (pow_root {suc i} i+1/=0 (<=-less A3)) (rewrite {1} *-comm (rewriteI (*-assoc {RealField}) (rewrite OrderedField.pinv-right ide-left)))
              \in inP (i, r0new, root>0 i+1/=0 A3, A4, \lam l _ =>
                \case LinearOrder.Dec.trichotomy (l + {NatSemiring} suc m) n \with {
                  | less _ => absurd linarith
                  | equals A5 => rewrite (L3 {n} {suc m} A5) linarith
                  | greater A5 =>
                    \let
                      | A6 => A1 l (<_suc_<= linarith)
                      | l+1/=0 : suc l /= {Nat} 0 => \case __
                    \in rewrite A4 (rewriteI A0 ((<=_+ (<=_*_positive-right (ai>=0 l)
                      (<=-less (LinearlyOrderedSemiring.pow_<-monotone l+1/=0 (<=-less (root>0 i+1/=0 A3)) r0new<r0))) (<=-refl {RealField} {negative eps})) <∘r A6))
                })
            | ||.byRight A2 => inP (k0, r0, r0>0, A0, \lam l _ =>
              \case LinearOrder.Dec.trichotomy (l + {NatSemiring} suc m) n \with {
                | less A4 => absurd linarith
                | greater A4 => A1 l (<_suc_<= linarith)
                | equals A4 => rewrite A0 (<_+-left (negative eps) (rewrite (L3 {n} {suc m} A4) in A2))
              } )
          }
    }
}

{- | Stabilization Lemma (Pigeonhole Principle)
A non-increasing sequence in a finite set of cardinality $n+1$ must have three consecutive equal values
if the sequence is at least $2n+3$ elements long. -}
\lemma three-consecutive-equals {n N : Nat} (N>2n : N > 2 * n)
                                (k : Fin (N + 2) -> Fin (suc n))
                                (monotone : \Pi (j : Fin (suc N)) -> k (suc j) <= {NatSemiring} k j) :
  ∃ (j : Fin N) (k j = k (suc j)) (k (suc j) = k (suc (suc j))) =>
  helper n N N>2n k (<_suc_<= (fin_< (k 0))) monotone \where {
  \lemma helper {n : Nat} (b N : Nat) (N>2b : N > 2 * b)
                (k : Fin (suc (suc N)) -> Fin (suc n))
                (k0<=b : (k 0 : Nat) <= b)
                (monotone : \Pi (j : Fin (suc N)) -> k (suc j) <= {NatSemiring} k j) :
    TruncP (\Sigma (j : Fin N) (k j = k (suc j)) (k (suc j) = k (suc (suc j)))) \elim b, N, N>2b
    | _, 0, ()
    | 0, suc N', _ =>
      \let | k0=0 : (k 0 : Nat) = 0 => <=-antisymmetric k0<=b zero<=_
           | k1<=0 : (k 1 : Nat) <= 0 => <=-transitive (monotone 0) k0<=b
           | k1=0 : (k 1 : Nat) = 0 => <=-antisymmetric k1<=0 zero<=_
           | k2<=0 : (k 2 : Nat) <= 0 => <=-transitive (monotone 1) k1<=0
           | k2=0 : (k 2 : Nat) = 0 => <=-antisymmetric k2<=0 zero<=_
      \in inP (0, fin_nat-inj (k0=0 *> inv k1=0), fin_nat-inj (k1=0 *> inv k2=0))
    | suc b', 1, NatOrder.suc<suc p => \case p
    | suc b', suc (suc N'), N>2b =>
      \case LinearOrder.Dec.trichotomy {FinOrder (suc n)} (k 0) (k 1) \with {
        | Tri.less k0<k1 => absurd (monotone 0 k0<k1)
        | Tri.equals k0=k1 =>
          \case LinearOrder.Dec.trichotomy {FinOrder (suc n)} (k 1) (k 2) \with {
            | Tri.less k1<k2 => absurd (monotone 1 k1<k2)
            | Tri.equals k1=k2 => inP (0, k0=k1, k1=k2)
            | Tri.greater k1>k2 =>
              \let | k1<=suc-b' : (k 1 : Nat) <= suc b' => transport (\lam x => (x : Nat) <= suc b') k0=k1 k0<=b
                   | k2<k1 : (k 2 : Nat) < (k 1 : Nat) => k1>k2
                   | k2<=b' : (k 2 : Nat) <= b' => <_suc_<= (k2<k1 <∘l k1<=suc-b')
                   | k'' : Fin (suc (suc N')) -> Fin (suc n) => \lam j => k (suc (suc j))
                   | N'>2b' : N' > 2 * b' => NatOrder.unsuc< (NatOrder.unsuc< N>2b)
              \in \case helper {n} b' N' N'>2b' k'' k2<=b' (\lam j => monotone (suc (suc j))) \with {
                | inP (j, eq1, eq2) => inP (suc (suc j), eq1, eq2)
              }
          }
        | Tri.greater k0>k1 =>
          \let | k1<k0 : (k 1 : Nat) < (k 0 : Nat) => k0>k1
               | k1<=b' : (k 1 : Nat) <= b' => <_suc_<= (k1<k0 <∘l k0<=b)
               | k' : Fin (suc (suc (suc N'))) -> Fin (suc n) => \lam j => k (suc j)
               | N'>2b' : suc N' > 2 * b' => <-transitive id<suc (NatOrder.unsuc< N>2b)
          \in \case helper {n} b' (suc N') N'>2b' k' k1<=b' (\lam j => monotone (suc j)) \with {
            | inP (j, eq1, eq2) => inP (suc j, eq1, eq2)
          }
      }
}

-- ! Should be proved through geometric-partial-sum'

\lemma geom_sum_upper {n m : Nat} (m<=n : m <= n) :
  AddMonoid.BigSum {RealAbGroup} (\lam (i : Fin m) => pow {RealField} (ratio 1 3) (suc i)) <=
  Real.fromRat (ratio 1 2) * (Real.fromRat 1 - pow {RealField} (ratio 1 3) n) =>
  \let A0 => Ring.geometric-like-partial-sum {RealField} {1} {m} {ratio 1 3} \in linarith (pow1/3-monotone m<=n)

-- ! Should be proved through geometric-partial-sum

\lemma geom_sum_upper' {n m : Nat} (m<=n : m <= n) :
  AddMonoid.BigSum {RealAbGroup} (\lam (i : Fin m) => pow {RealField} (ratio 1 3) i) <=
  Real.fromRat (ratio 3 2) * (Real.fromRat 1 - pow {RealField} (ratio 1 3) n) =>
  linarith (Ring.geometric-partial-sum {RealField} {m} {ratio 1 3}, pow1/3-monotone m<=n)

\lemma MainLemma {n : Nat} (n>0 : n > 0) (eps : Real) (eps>0 : eps > 0)
                 (a : Array Real (suc (suc n)))
                 (a0>eps : a 0 > eps)
                 (ai>=0 : \Pi (i : Fin (suc n)) -> a (suc i) >= 0)
                 (an=1 : a (suc n) = {RealField} 1) :
  ∃ (r : Real) (r>0 : r > 0) (k : Fin (suc n))
  (pow {RealField} r (suc n) < a 0)
  (pow {RealField} (ratio 1 3) (2 * suc n * suc n) * a 0 - 2 * eps < a (suc k) * pow {RealField} r (suc k))
  (a (suc k) * pow {RealField} r (suc k) < a 0)
  (AddMonoid.BigSum (\new Array Real k (\lam i => a (i Nat.+ 1) * pow r (suc i) )) +
  AddMonoid.BigSum (\new Array Real (n -' k) (\lam i => a (suc (suc k Nat.+ i)) * pow r (suc (suc k Nat.+ i)) ))
    < a (suc k) * pow r (suc k) * (Real.fromRat 1 - pow one/3 (suc n)) + eps * pow 3 (suc n)) =>
  \case KeyLemma {n} eps eps>0 a a0>eps ai>=0 an=1 \with {
    | inP (r0, r0>0, kSeq, k_mono, C1, C2) =>
      \case three-consecutive-equals {n} {2 * n + 2} linarith kSeq
              (\lam j => rewrite (nat_fin_= (mod_< (NatOrder.suc<suc (fin_< j)))) in k_mono j) \with {
        | inP (j, eq1, eq2) =>
          \let
            | k : Fin (suc n) => kSeq j
            | r : Real => r0 * pow one/3 (suc j)
            | r>0 : r > 0 => LinearlyOrderedSemiring.<_*_positive_positive r0>0 (LinearlyOrderedSemiring.pow>0 {_} one/3>0 {suc j})
            | r>=0 : r >= 0 => <=-less r>0
            | r0>=0 : r0 >= 0 => <=-less r0>0
            | r<=r0 : r <= r0 => transport (r0 * pow one/3 (suc j) <=) (ide-right {RealField})
              (PosetSemiring.<=_*_positive-right (<=-less r0>0) pow_one/3<=1)
            | k0 : Fin (suc n) => kSeq 0
            | n_fin : Fin (suc n) => Fin.fromNat {n} n
            | a0_minus_eps_>0 : a 0 - eps > 0 => linarith
            | -2eps=-eps-eps : \Pi (x : RealField) -> x - (natCoef 2 * eps) = x - eps - eps => \lam _ => linarith
            | three_times_one_third : (3 : Real) * ratio 1 3 = {RealField} 1 => linarith
            | third^m*3^m=1 : \Pi (m : Nat) -> pow {RealField} one/3 m * pow 3 m = {Real} 1 =>
              \lam m => rewriteI CMonoid.pow_*-comm (rewrite (rewrite *-comm in three_times_one_third) Monoid.pow_ide)

            | ai_ri_<_a0 : \Pi (i : Fin (suc n)) -> a (suc i) * pow r (suc i) < a 0 =>
              \lam i => (PosetSemiring.<=_*_positive-right (ai>=0 i)
                (PosetSemiring.pow_<=-monotone {RealField} {r} {r0} {suc i} r>=0 r<=r0)) <∘r
              (rewrite (pmap (__ + eps) C1 *> +-assoc *> pmap (a 0 +) (negative-left {RealField}) *> zro-right) in
              (rewrite (+-assoc, negative-left {RealField}, zro-right) in
              <_+-left eps (rewrite ide-right in C2 0 i)))
            | h1 : a (suc k0) * pow r (suc k0) - eps >= (a 0 - eps) * pow one/3 (2 * suc n * suc n) - eps =>
              rewrite (pmap (a (suc k0) *) (CMonoid.pow_*-comm {RealField} {r0} {pow one/3 (suc j)} {suc k0} *>
              pmap (pow r0 (suc k0) *) (inv (Monoid.pow_* {RealField} {one/3} {suc j} {suc k0}))) *>
              inv (*-assoc {RealField}) *> pmap (`* pow one/3 ((suc j : Nat) * suc k0)) C1)
                (<=_+ (PosetSemiring.<=_*_positive-right (<=-less a0_minus_eps_>0)
                  (PosetSemiring.pow_<=-degree {RealField} one/3>=0 one/3<=1 {suc j Nat.* (suc (kSeq 0))} {2 * suc n * suc n}
                    (<=_* (suc<=suc (<_suc_<= (fin_< j))) (suc<=suc (<_suc_<= (fin_< k0)))))) <=-refl)

            | k+i<n : \Pi (i : Fin (n -' k)) -> k Nat.+ i < n => \lam i => <∘l (<_+-right k (fin_< i)) (rewrite (<=_exists (<_suc_<= (fin_< k))) <=-refl)

            | C2j+1 : \Pi (i : Fin (suc n)) -> a (suc k) * pow r (suc k) > a (suc i) * pow r (suc i) - eps =>
              rewrite (inv eq1) in C2 (suc j)
            | arr-one/3^i+1 => \new Array RealField (n -' k) (\lam i => pow one/3 (suc i))
            | arr-one/3^k+i+2 => \new Array RealField (n -' k) (\lam i => pow one/3 (suc (suc k) Nat.+ i))

            | A0 =>
              \let
                | helper1 : \Pi (i : Fin (n -' k)) -> Fin.fromNat {n} (suc (k Nat.+ i)) = {Nat} suc (k Nat.+ i) =>
                  \lam i => mod_< (NatOrder.suc<suc (k+i<n i))
                | helper2 : \Pi (i : Fin (n -' k)) -> Fin.fromNat {suc n} (suc (suc (k Nat.+ i))) = {Fin (suc (suc n))} suc (Fin.fromNat {n} (suc (k Nat.+ i))) =>
                  \lam i => fin_nat-inj (rewrite helper1 ( mod_< (NatOrder.suc<suc (NatOrder.suc<suc (k+i<n i)))))
                | C2j : \Pi (i : Fin (suc n)) ->
                  a (suc k) * pow (r * 3) (suc k) > a (suc i) * pow (r * 3) (suc i) - eps =>
                  rewrite (*-assoc, *-assoc, inv (*-comm {_} {3}), three_times_one_third, ide-right) (C2 j)
                | C2j' : \Pi (i : Fin (n -' k)) ->
                  a (suc (suc k Nat.+ i)) * pow r (suc (suc k Nat.+ i)) < a (suc k) * pow r (suc k) * pow one/3 (suc i) + eps * pow one/3 (suc (suc k Nat.+ i)) =>
                  \lam i => rewriteI (ide-right {RealField} {r}, three_times_one_third, *-assoc {_} {r})
                    (rewrite (CMonoid.pow_*-comm {_} {r * natCoef 3} {_} {suc (k Nat.+ suc i)}, CMonoid.pow_*-comm {_} {r * natCoef 3} {_} {suc k},
                              *-assoc {_} {a (suc k)} {pow (r * natCoef 3) (suc k) * pow one/3 (suc k)} {pow one/3 (suc i)},
                              *-assoc {_} {pow (r * natCoef 3) (suc k)} {pow one/3 (suc k)} {pow one/3 (suc i)},
                              inv (CMonoid.pow_+ {_} {one/3} {suc k} {suc i}))
                      (rewriteI (*-assoc {_} {a (suc k)} {pow (r * natCoef 3) (suc k)} {pow one/3 (suc (k Nat.+ suc i))},
                                 rdistr {_} {_} {_} {pow one/3 (suc k Nat.+ suc i)}, *-assoc {_} {a (suc k Nat.+ suc i)})
                        (<_*_positive-left {RealField} {_} {_} {pow one/3 (suc k Nat.+ suc i)}
                          (OrderedAddGroup.<-diff-mid (later $ rewrite helper2 (rewrite {2} (helper1 i) in C2j (k Nat.+ suc i))))
                          (OrderedSemiring.pow>0 one/3>0 {suc k Nat.+ suc i}))))
              \in PosetAddMonoid.BigSum_<= {RealField} {n -' k} {\lam i => a (suc (suc k Nat.+ i)) * pow r (suc (suc k Nat.+ i))}
                {\lam i => a (suc k) * pow r (suc k) * pow one/3 (suc i) + eps * pow one/3 (suc (suc k Nat.+ i)) } (\lam i => <=-less (C2j' i))

            | arr-one/3^k-i => \new Array RealField k (\lam i => pow one/3 (k -' i))
            | arr-3^i+1 => \new Array RealField k (\lam i => pow 3 (suc i))
            | A1 =>
              \let
                | three>0 : zro < {RealField} natCoef 3 => linarith
                | helper : \Pi (i : Fin (suc k)) -> suc (fin-inc_<= (suc_<_<= (fin_< k)) i) = {Fin (suc (suc n))} Fin.fromNat {suc n} (suc i) => \lam i =>
                  fin_nat-inj (rewrite toFin=id (inv (mod_< (NatOrder.suc<suc (<∘l (fin_< i) (<_suc_<= (NatOrder.suc<suc (fin_< k))))))))
                | C2j+2 : \Pi (i : Fin (suc n)) -> a (suc k) * pow (r * one/3) (suc k) > a (suc i) * pow (r * one/3) (suc i) - eps =>
                  rewrite (inv eq2, inv eq1, *-assoc, inv (*-assoc {_} {r0}),
                           inv (*-assoc {_} {r0 * pow one/3 j}), *-assoc {_} {r0}) in C2 (suc (suc j))
                | C2j+2' : \Pi (i : Fin (suc k)) -> a (suc (i : Nat)) * pow r (suc i) < a (suc k) * pow r (suc k) * pow one/3 (k -' i) + eps * pow 3 (suc i) =>
                  \lam i => rewriteI (ide-right {_} {pow r (suc i)}, ide-right {_} {pow one/3 (k -' i)}, third^m*3^m=1 (suc i))
                    (rewriteI (*-assoc {_} {pow one/3 (k -' i)} {pow one/3 (suc i)}, Monoid.pow_+ {RealField} {one/3} {k -' i} {suc i})
                      (rewrite (+-comm {_} {k -' i} {i}, <=_exists (<_suc_<= (fin_< i)))
                        (rewriteI (*-assoc {RealField} {a (suc k) * pow r (suc k)} {pow one/3 (suc k)} {pow 3 (suc i)})
                          (repeat {2} (rewriteI *-assoc) (rewriteI rdistr (<_*_positive-left
                            (rewrite (*-assoc, inv (CMonoid.pow_*-comm {RealField} {r} {one/3} {suc i}))
                              (rewrite (*-assoc {RealField} {a (suc k)} {pow r (suc k)} {pow one/3 (suc k)}, inv (CMonoid.pow_*-comm {RealField} {r} {one/3} {suc k}))
                                (OrderedAddGroup.<-diff-mid
                                  (later $ (rewrite (helper i, toFin=id) in C2j+2 (fin-inc_<= {suc k} {suc n} (suc_<_<= (fin_< k)) i))))))
                            (OrderedSemiring.pow>0 three>0 {suc i})))))))
              \in PosetAddMonoid.BigSum_<= {RealField} {k} {\lam i => a (suc (i : Nat)) * pow r (suc i)} {\lam i => a (suc k) * pow r (suc k) * pow one/3 (k -' i) + eps * pow 3 (suc i) } (\lam i => <=-less (C2j+2' i))

            | A2 : a (suc k) RealField.* (pow r k * r) * AddMonoid.BigSum arr-one/3^k-i + eps * AddMonoid.BigSum arr-3^i+1 +
            (a (suc k) RealField.* (pow r k * r) * AddMonoid.BigSum arr-one/3^i+1 + eps * AddMonoid.BigSum arr-one/3^k+i+2) =
            (a (suc k) RealField.* (pow r k * r)) * (AddMonoid.BigSum arr-one/3^k-i + AddMonoid.BigSum arr-one/3^i+1) +
            eps * (AddMonoid.BigSum arr-3^i+1 + AddMonoid.BigSum arr-one/3^k+i+2) => equation.ring
            | A3 : a (suc k) * pow {RealField} r (suc k) >= 0 =>
              PosetSemiring.<=_*_positive_positive {RealField} (ai>=0 k) (PosetSemiring.pow>=0 {_} {r} {suc k} r>=0)
            | A4 : AddMonoid.BigSum arr-one/3^k+i+2 <= ide =>
              \let
                | helper : (\lam (i : Fin (n -' k)) => pow one/3 (suc (suc k) Nat.+ i)) = (\lam i => pow one/3 (suc k) * pow one/3 (suc i)) => ext (\lam i => rewrite Monoid.pow_+ equation.cMonoid)
                | one/3^k+1<=1 : pow one/3 (suc k) <= ide => <=-less (pow1/3-strict-monotone {_} NatOrder.zero<suc)
                | one/3^n>=0 : pow {RealField} (ratio 1 3) n >= 0 => <=-less (OrderedSemiring.pow>0 one/3>0)
                | one-1/3^n<=1 : Real.fromRat 1 - pow {RealField} (ratio 1 3) n <= ide => linarith
                | one-1/3^n>=0 : Real.fromRat 1 - pow {RealField} (ratio 1 3) n >= zro =>
                  rewriteI (negative-right {RealField} {pow {RealField} (ratio 1 3) n}) (<=_+ (PosetSemiring.pow<=1 one/3>=0 one/3<=1) <=-refl )
                | B0 : AddMonoid.BigSum arr-one/3^k+i+2 <= (pow one/3 (suc k) * (Real.fromRat (ratio 1 2) * (Real.fromRat 1 - pow {RealField} (ratio 1 3) n)) ) =>
                  unfold arr-one/3^k+i+2 (rewrite (helper, inv (Semiring.BigSum-ldistr {_} {pow one/3 (suc k)} {\new Array RealField (n -' k) (\lam i => pow one/3 (suc i))}))
                    (<=_*_positive-right {RealField} {pow one/3 (suc k)} (<=-less (OrderedSemiring.pow>0 one/3>0 {suc k})) (geom_sum_upper {n} {n -' k} -'<=id)))
                | B1 => rewrite *-assoc in (rewrite ide-left in (<=_*_positive-left (rewrite ide-left in <=_*_positive-left {RealField} one/3^k+1<=1 one/2>=0) one-1/3^n>=0) <=∘
                                                                (<=_*_positive-left one/2<=1 one-1/3^n>=0)) <=∘ one-1/3^n<=1
              \in <=∘ B0 B1
            | A5 : AddMonoid.BigSum arr-one/3^k-i + AddMonoid.BigSum arr-one/3^i+1 <= 1 - pow one/3 (suc n) =>
              \let
                | arr5' => \new Array RealField (suc k) (\lam i => pow one/3 i)
                | helper : (\lam (i : Fin k) => pow one/3 ((kSeq j -' i) Nat.mod suc (kSeq j))) = (\lam (i : Fin k) => pow {RealField} one/3 (kSeq j -' i)) => ext (\lam i => rewrite (mod_< {k -' i} {suc k} (<=_<_suc -'<=id)) idp)
                | B0 : AddMonoid.BigSum arr-one/3^i+1 <= Real.fromRat (ratio 1 2) * (Real.fromRat 1 - pow {RealField} (ratio 1 3) n) => geom_sum_upper {n} {n -' k} -'<=id
                | B1 : AddMonoid.BigSum arr-one/3^k-i = AddMonoid.BigSum arr5' - ide => rewrite (+-assoc, negative-right, zro-right) in
                pmap (__ - ide) (rewrite (AddMonoid.BigSum_suc, mod_< id<suc, -'id, helper) in AbMonoid.BigSum-reverse arr5')
                | B2 : AddMonoid.BigSum arr-one/3^k-i <= Real.fromRat (ratio 3 2) * (Real.fromRat 1 - pow {RealField} (ratio 1 3) (suc n)) - ide =>
                  rewrite B1 (<=_+ (geom_sum_upper' {suc n} {suc k} (suc_<_<= (fin_< k)) ) (<=-refl {_} {negative ide}))
              \in linarith (pow1/3-strict-monotone id<suc)

            | helper5 : ide - natCoef 3 = {RealField} negative (natCoef 2) => linarith
            | arr8_computation : negative 2 * AddMonoid.BigSum arr-3^i+1 = 3 - pow 3 (suc k) => rewrite (helper5, ide-left) in Ring.geometric-like-partial-sum {RealField} {1} {k} {natCoef 3}

          \in inP (r, r>0, k,
                   rewrite (pmap (a (suc n_fin) *) (pmap (pow r) (pmap suc (mod_< id<suc))) *>
                   pmap (`* pow r (suc n)) (pmap a (fin_nat-inj {suc (suc n)} {suc n_fin} {Fin.fromNat {suc n} (suc n)}
                     (unfold Fin.fromNat (rewrite (mod_< id<suc, mod_< id<suc) idp))) *> an=1) *> ide-left) in
                   ai_ri_<_a0 n_fin,
                   (<=-transitive (later $ rewrite -2eps=-eps-eps (<=_+
                     (rewrite (rdistr, inv (*-comm {RealField} {a 0}))
                       (<=_+ (<=-refl {RealField} {a 0 * _}) (rewrite {1} (inv (ide-right {_} {negative eps}))
                         (<=-less ( <_*_negative-right {_} {negative eps} (OrderedAddGroup.positive_negative eps>0)
                           (pow1/3-strict-monotone {2 * suc n * suc n} NatOrder.zero<suc))))))
                     (<=-refl {_} {negative eps}))) h1) <∘r (C2j+1 k0),
                   ai_ri_<_a0 k,
                   (<=_+ A1 A0) <∘r
                   (rewrite (AbMonoid.BigSum_+ {RealField} {n -' k} {\new Array RealField (n -' k) (\lam i => a (suc k) * pow r (suc k) * pow one/3 (suc i))} {\new Array RealField (n -' k) (\lam i => eps * pow one/3 (suc (suc k) Nat.+ i))},
                             AbMonoid.BigSum_+ {RealField} {k} {\new Array RealField k (\lam i => a (suc k) * pow r (suc k) * pow one/3 (k -' i))} {\new Array RealField k (\lam i => eps * pow 3 (suc i))},
                             inv (Semiring.BigSum-ldistr {_} {a DArray.!! suc k RealField.* (pow {RealField} r (suc k))} {arr-one/3^i+1}),
                             inv (Semiring.BigSum-ldistr {_} {eps} {arr-one/3^k+i+2}),
                             inv (Semiring.BigSum-ldistr {_} {a DArray.!! suc k RealField.* (pow {RealField} r (suc k))} {arr-one/3^k-i}),
                             inv (Semiring.BigSum-ldistr {_} {eps} {arr-3^i+1}), A2)
                     (LinearlyOrderedAbMonoid.<=_+-left (<=_*_positive-right A3 A5)
                       ( <_*_positive-right eps>0 {?})))) -- to be filled later
      }
  }